name: Docker Build
on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  push_to_registries:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: srzzumix/unityhub:latest
      - name: Push to version tag
        env:
          DOCKER_TAG: latest
          IMAGE_NAME: srzzumix/unityhub
          DOCKER_REPO: srzzumix/unityhub
        run: |
          ./hooks/post_push
            
